all:
	g++ density.cpp senDensity.cpp -o sendensity -mfpu=neon
compile:
#add -mfpu=neon for RaspberryPi
#chANGE directory when change folder
#g++ -std=c++11 `pkg-config --cflags opencv` density.cpp senDensity.cpp -o sendensity -ljpeg -march=nehalem `pkg-config --libs opencv`
