all:
	g++ -std=c++11 ReceiveDensity.cpp -o receivedensity -ljpeg
compile:
#add -mfpu=neon for RaspberryPi
#chANGE directory when change folder
#g++ -std=c++11 `pkg-config --cflags opencv` ReceiveDensity.cpp receive.cpp -o receiveDensity -ljpeg -march=nehalem `pkg-config --libs opencv`
